# This worflow file is executed everytime there is a 'push' to the 'main' barnch
name: TestCafe Workflow
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run TestCafe & Generate Report
    runs-on: ubuntu-latest #Get the latest available 'Ubuntu' machine to run the Workflow on (through the GithubActions)

    steps:
      - name: Checkout code #Branch Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js #Install 'Node.js' as the most important prerequisite for exceuting the 'Testcafe' test scripts in general (not only on ghActions)
        uses: actions/setup-node@v3

      - name: Install dependencies #Install all the project's dependencies mentioned in the 'package.json' 
        run: npm install

      - name: Run TestCafe tests and generate HTML report
        run: |
          npm run test:ghactions || true 
 #This command will execute the 'test:ghactions' script which is part of the 'scripts' section in the 'package.json' 
 #This will run the scripts then generate html report      
 # we need to remove the part (|| true) in production, This part was added only to mark the workflow as passed in all cases
     
      - name: Deploy report to Github Pages #Deploy the genarted html report to the 'Github_Pages' in order to be easily accessible
        if: always() 
        #This means regardless of the previous step output, this step will be executed
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }} #The GitHub Actions generated token for the workflow to be able to deploy the output to the GitHubPages
          PUBLISH_BRANCH: gh-pages #The branch at which the report will be published to (needs to be spearate branch)
          PUBLISH_DIR: ./reports #This is the directory at which the html report was generated
